apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-pv-claim
  labels:
    app: phpmyadmin-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
