apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    name: phpmyadmin-service
    app: phpmyadmin
spec:
  ports:
  - port: 80
    targetPort: 80
    name: pma-http
  - port: 443
    targetPort: 443
    name: pma-https
  type: LoadBalancer 
  selector:
    name: phpmyadmin-pod
    app: phpmyadmin